name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install gdal-bin

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Type-check with Pyright
        run: uv run pyright .

      - name: Lint with ruff
        run: uv run ruff check --output-format=github .

      - name: Format with ruff
        run: uv run ruff format .
